module.exports = {
	defaultSeverity: "warning",
	ignoreFiles: [".git/**", "**/node_modules/**"],
	plugins: ["stylelint-scss"],
	extends: [
		"stylelint-config-standard",
		"stylelint-config-standard-scss",
		"stylelint-config-recommended",
		"stylelint-config-sass-guidelines"
	],
	rules: {
		"selector-class-pattern": null,
		"property-no-vendor-prefix": null,
		"order/properties-alphabetical-order": null,
		"string-quotes": "double",
		"order/order": null,
		"max-nesting-depth": 3,
		"declaration-block-trailing-semicolon": ["always", { severity: "error" }],
		linebreaks: "unix",
		indentation: ["tab"],
		"color-hex-case": "upper",
		"no-duplicate-selectors": true,
		"color-hex-length": "short",
		"color-named": "never",
		"selector-no-qualifying-type": true,
		"selector-max-id": [0, { severity: "warn" }],
		"selector-max-attribute": [0, { severity: "warn" }],
		"selector-combinator-space-after": "always",
		"selector-attribute-quotes": "always",
		"selector-attribute-brackets-space-inside": "never",
		"custom-property-empty-line-before": null,
		"declaration-no-important": true,
		"declaration-colon-space-before": "never",
		"value-no-vendor-prefix": null,
		"number-leading-zero": "always",
		"function-url-quotes": "always",
		"font-family-name-quotes": "always-where-required",
		"comment-empty-line-before": "always",
		"at-rule-no-vendor-prefix": null,
		"rule-empty-line-before": "always",
		"selector-pseudo-element-colon-notation": "double",
		"selector-pseudo-class-parentheses-space-inside": "never",
		"selector-max-type": [0, { severity: "warn" }],
		"media-feature-range-operator-space-before": "always",
		"media-feature-range-operator-space-after": "always",
		"media-feature-parentheses-space-inside": "never",
		"media-feature-name-no-vendor-prefix": true,
		"media-feature-colon-space-before": "never",
		"media-feature-colon-space-after": "always",
		"max-empty-lines": 1
	}
};
